[versions]
agp = "8.7.2"
kotlin = "2.0.21"
ksp="2.0.21-1.0.26"
coreKtx = "1.15.0"
dagger="2.52"
lifecycleRuntimeKtx = "2.8.7"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
dagger-hilt = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = {id = "com.google.devtools.ksp", version.ref="ksp"}

